In [14]:
import pandas as pd
import numpy as np

In [15]:
CCDdata = pd.read_sas('/Users/rileylatham/Downloads/Independent_Study/Data_Pool/Common Core data/sdf001d.sas7bdat',
                     encoding='unicode_escape')

In [17]:
col_chg = {'Z32':'TotalSalaries', 'Z34':'TotalEmployeeBenefits'}

CCDdata = CCDdata.rename(columns=col_chg)

CCDdata = CCDdata[['LEAID', 'CENSUSID', 'FIPST', 'FIPSCO', 'CMSA', 'STNAME', 'STABBR', 'SCHLEV', 'AGCHRT',
                  'TOTALREV', 'TFEDREV', 'TSTREV', 'TLOCREV', 'TOTALEXP', 'TCURELSC', 'TCURINST', 
                  'TCURSSVC', 'TCUROTH', 'TNONELSE', 'TCAPOUT', 'TotalSalaries', 'TotalEmployeeBenefits']]

In [18]:
SASSdata = pd.read_csv('/Users/rileylatham/Downloads/Independent_Study/Data_Pool/SASS data/Clean_SASS.csv')

In [19]:
def str_to_int(data):
    for col in data:
        j=0
        for i in data[col]:
            if str(i).isdigit():
                data.at[j,col] = int(i)
                j+=1
            else:
                pass
                j+=1
    return data

In [20]:
str_to_int = str_to_int(CCDdata)
str_to_int = str_to_int.dropna(axis=0)

In [21]:
def LEAID_merge(SASS, CCD):
    j=186
    for val in CCD['LEAID']:
        CCD.at[j, 'LEAID'] = str(val)
        j+=1
    data = CCD[CCD['LEAID'].isin(SASS['CCDIDLEA'])]
    return data

In [22]:
matched_data = LEAID_merge(SASSdata, str_to_int).dropna(axis=0)

//anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:2909: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[index, col] = value

In [23]:
matched_data.to_csv(r'/Users/rileylatham/Downloads/Independent_Study/Data_Pool/Common Core data/Clean_CCD.csv',
                    header=True, index=False)

In [24]:
matched_data

,LEAID,CENSUSID,FIPST,FIPSCO,CMSA,STNAME,STABBR,SCHLEV,AGCHRT,TOTALREV,...,TLOCREV,TOTALEXP,TCURELSC,TCURINST,TCURSSVC,TCUROTH,TNONELSE,TCAPOUT,TotalSalaries,TotalEmployeeBenefits
186,100005,1504840100000,1,95,0,ALABAMA,AL,3,3,21871000.0,...,6930000.0,24097000.0,19205000.0,12150000.0,5816000.0,1239000.0,291000.0,4010000.0,12277000.0,3219000.0
187,100006,1504800100000,1,95,0,ALABAMA,AL,3,3,46349000.0,...,12863000.0,45411000.0,38662000.0,22503000.0,12891000.0,3268000.0,1568000.0,4087000.0,25233000.0,6746000.0
188,100007,1503740100000,1,73,1000,ALABAMA,AL,3,3,97598000.0,...,56150000.0,121021000.0,62253000.0,37504000.0,21015000.0,3734000.0,1807000.0,50284000.0,39563000.0,10794000.0
192,100090,1500800200000,1,15,450,ALABAMA,AL,3,3,18820000.0,...,3842000.0,19399000.0,18075000.0,10024000.0,5937000.0,2114000.0,384000.0,912000.0,11504000.0,3076000.0
193,100100,1504880100000,1,95,0,ALABAMA,AL,3,3,15400000.0,...,4214000.0,16735000.0,14025000.0,8878000.0,4309000.0,838000.0,308000.0,2402000.0,9435000.0,2418000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15463,5605695,49504300100000,54,85,0,WEST VIRGINIA,WV,3,3,13549000.0,...,2964000.0,14158000.0,13457000.0,8079000.0,4274000.0,1104000.0,62000.0,590000.0,7963000.0,3100000.0
15464,5605700,49504400100000,54,87,0,WEST VIRGINIA,WV,3,3,20216000.0,...,2819000.0,20134000.0,18472000.0,11055000.0,5755000.0,1662000.0,348000.0,1023000.0,11215000.0,4638000.0
15465,5605762,49504500100000,54,89,0,WEST VIRGINIA,WV,3,3,13147000.0,...,1592000.0,12975000.0,11769000.0,7266000.0,3829000.0,674000.0,286000.0,882000.0,7364000.0,3179000.0
15466,5605820,49504600100000,54,91,0,WEST VIRGINIA,WV,3,3,19631000.0,...,4227000.0,18792000.0,17801000.0,10716000.0,6134000.0,951000.0,32000.0,609000.0,10986000.0,4726000.0
15467,5605830,49504700100000,54,93,0,WEST VIRGINIA,WV,3,3,8708000.0,...,2132000.0,8884000.0,8431000.0,4968000.0,2853000.0,610000.0,17000.0,433000.0,4942000.0,2045000.0