In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_sas('/Users/rileylatham/Downloads/Independent_Study/Data_Pool/SASS data/distpub99.sas7bdat',
                  encoding='utf-8')

In [4]:
# Change Column names to more recognizable names
# Comes from data dictionary
col_chg = {"AG_ENDYR":'FiscalYear', "AG_NOSCH":'NumSchools', "AG_RANKN":'NationSizeRank', 
          "AG_CMSA":'CMSACode', "AG_MSC":'MetroCode', "AG_RANKS":'StateSizeRank', "AG_SAGID":'StateAgencyID',
          "AG_STRYR":'SchoolYear-Fall', "C_COREPP":'CoreExpendPerPupil', "C_CPPERN":'CEPPNationRank', 
          "C_CPPERS":'CEPPStateRank', "C_CUREXP":'TotalCurrExpend', "C_CURINP":'PercExpendInstruction',
          "C_CURPPE":'CurrExpendPerPupil', "C_FEDREV":'TotalFedRev', "C_FEDRVP":'PercRevFederal', 
          "C_LOCREV":'TotLocalRev', "C_LOCRVP":'PercRevLocal', "C_POVPOP":'RelatedChildreninPoverty',
          "C_SALINP":'PercExpendInstructorSalary', "C_SALTOP":'PercExpendSalaries', "C_SCHPOP":'KidsinDistrict',
          "C_STREV":'TotStateRev', "C_STREVP":'PercRevState', "C_TCURIN":'TotExpendInstruction',
          "C_TOTEXP":'DistrictTotExpend', "C_TOTPOP":'TotPopinDistrict', "C_TOTPPE":'TotExpendperPupil', 
          "C_Z32":'TotalSalariesandWages', "C_Z33":'InstructionalSalaries', "CONTEA":'NumContinueTeachers', 
          "D0452":'Gr1-12orNot', "D0450":'DistrictOrLEA',"D0453":'MergedDistrict', "D0454":'BeginTime', 
          "D0456":'TotalEnrollment',"D0457":'EnrollK-12', "D0458":'HispanicStudents', "D0459":'WhiteStudents',
          "D0460":'BlackStudents', "D0461":'AmericanIndianStudents', "D0462":'AsianStudents',
          "D0463":'K-12byRace', "D0464":'EligFreeLunch', "D0466":'EligFreeLunchK-12', "D0467":'ParticLunchProg',
          "D0469":'ApprovedK-12', "D0470":'DaysSchYr', "D0471":'HispanicTeachers', "D0472":'WhiteTeachers',
          "D0473":'BlackTeachers', "D0474":'AmericanIndianTeachers', "D0475":'AsianTeachers',
          "D0476":'FTETeachersCnt', "D0487":'NewTeacherHires', "D0495":'DismissedTeachers<4yrs',
          "D0496":'DismissedTeachers>4yrs', "D0497":'UnionAgreement', "D0498":'AgreementType',
          "D0499":'TeacherContractYear', "D0500":'SalarySchedule', "D0501":'BA-NoExp', "D0502":'BA-10yrs',
          "D0503":'MS-NoExp', "D0504":'MS-30Cr', "D0505":'MS-20yrs', "D0506":'HighestSteponSalarySchd',
          "D0507":'LowestSalary', "D0508":'HighestSalary', "D0509":'BenefitRateTeacher',
          "D0510":'BenefitRateNonProf', "D0511":'Benefit-Admin-Same/Other', "D0512":'BenefitAdminRate',
          "D0513":'Benefit-Aides-Same/Other', "D0514":'BenefitRateAides', "D0515":'OtherAgencyContribrute', 
          "D0516":'OtherAgencyContributeRate', "D0517":'Benefit-Medical', "D0518":'Benefit-Dental',
          "D0519":'Benefit-Life', "D0520":'Benefit-Housing', "D0521":'Benefit-Meal',
          "D0522":'Benefit-Transport', "D0553":'HasCharter', "D0554":'NumCharter', "D0641":'MigrantStudentLstYr',
          "D0642":'MigrantStudentLstSmr', "D0643":'NumMigrantStudent', "NMINST_D":'NumMinorityStudentsDistrict', 
          "NMINTCH":'NumMinorityTeachers', "NSLAPP":'PercStudApprovedLunchDisc',
          "NSLELG":'PercStudEligLunchDisc', "STATABB":'StateAbb'}

# Rename
data = data.rename(columns=col_chg)

drop_1 = ['D0451', 'D0455', 'D0465', 'D0468', 'D0488', 'D0489', 'D0490', 'D0491']

drop_2 = list(data.columns[98:208])

drop_3 = list(data.columns[221:309])

drop_all = drop_1 + drop_2 + drop_3

data_clean_bytes = data.drop(drop_all, axis=1)

In [5]:
def str_to_int(data):
    for col in data:
        j=0
        for i in data[col]:
            if str(i).isdigit():
                data.at[j,col] = int(i)
                j+=1
            else:
                pass
                j+=1
    return data

str_int_data = str_to_int(data_clean_bytes)

str_int_data

,CMSACode,FiscalYear,MetroCode,NumSchools,NationSizeRank,StateSizeRank,StateAgencyID,SchoolYear-Fall,C_C14,CoreExpendPerPupil,...,PercStudApprovedLunchDisc,PercStudEligLunchDisc,REGION,StateAbb,STATE,STCNTY,SURVEY,URBANID,CNTLNUM,DFNLWGT
0,0,1998,3,6.0,3035.0,67.0,101,1997,506000.0,3582.0,...,41.52,41.52,3,AL,1,1095,1,3.0,104534,1.6829
1,0,1998,3,14.0,1271.0,26.0,48,1997,1168000.0,3087.0,...,46.89,46.89,3,AL,1,1095,1,3.0,102232,1.2018
2,1000,1998,2,11.0,910.0,15.0,158,1997,145000.0,3733.0,...,5.00,5.00,3,AL,1,1073,1,2.0,103126,1.0000
3,450,1998,1,9.0,2965.0,62.0,105,1997,852000.0,3484.0,...,83.47,83.47,3,AL,1,1015,1,1.0,100665,1.7727
4,0,1998,3,4.0,3564.0,79.0,106,1997,122000.0,3071.0,...,14.82,15.54,3,AL,1,1095,1,3.0,104627,1.8200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4685,0,1998,3,3.0,10909.0,40.0,724000,1997,25000.0,5407.0,...,21.35,29.46,4,WY,56,56013,1,3.0,103857,1.5319
4686,0,1998,3,14.0,2874.0,7.0,1902000,1997,149000.0,4544.0,...,16.51,16.51,4,WY,56,56037,1,3.0,102955,1.1129
4687,0,1998,3,3.0,13175.0,49.0,2202000,1997,33000.0,6971.0,...,49.62,49.62,4,WY,56,56043,1,3.0,104093,1.9385
4688,0,1998,3,10.0,4251.0,12.0,2001000,1997,0.0,4387.0,...,7.41,7.41,4,WY,56,56039,1,3.0,104379,1.1129
4689,0,1998,3,1.0,14143.0,51.0,2050001,1997,-9.0,-9.0,...,90.48,90.48,4,WY,56,56039,1,3.0,100279,1.1383

In [7]:
def string_check(data):
    '''Checks for string values and returns columns which contain them.
    These must be excluded before running regressions.'''
    col_list = []
    for col in data:
        for i in data[col]:
            if isinstance(i, str):
                col_list.append(col)
    return set(col_list)

exc_list = string_check(str_int_data)
print(exc_list)

{'StateAgencyID', 'CCDIDLEA', 'StateAbb', 'SchoolYear-Fall', 'MetroCode', 'CMSACode', 'FiscalYear'}

In [8]:
# Split our data to let us predict instructer salaries

fin_data = str_int_data.drop(['StateAbb', 'StateAgencyID', 'CMSACode',
              'CCDIDLEA', 'SchoolYear-Fall', 'FiscalYear',
              'MetroCode'], axis=1)

In [9]:
fin_data.to_csv(r'/Users/rileylatham/Downloads/Independent_Study/Data_Pool/SASS data/Clean_SASS.csv', 
               header=True, index=False)